!cloudgene.mapred.util.Settings
name: DAFF Biosecurity workflows
adminMail: ""
adminName: ""
apps: !java.util.Vector
-  filename: /mnt/data/taxodactyl/cloudgene.yml
   permission: user
externalWorkspace: 
   location: workspace
   type: local
maxRunningJobsPerUser: 1
navigation: !java.util.Vector
- !cloudgene.mapred.util.MenuItem
   id: download
   name: Download
   link: /download
- !cloudgene.mapred.util.MenuItem
   id: help
   name: Help
   link: http://docs.cloudgene.io
secretKey: pxtZvfhfVemQIDsHYjxSdAkDHNUdMEELQjkrUIlAfXKqwmnXKofvoVXEUshVKVIY
threadsQueue: 1
